# Generated by Django 4.0.6 on 2022-07-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_description_alter_quiz_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.IntegerField()),
                ('q_type', models.CharField(choices=[('sing', 'Single choice'), ('mult', 'Multiple choice'), ('open', 'Open ended')], max_length=4)),
                ('text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz')),
            ],
        ),
    ]
