# Generated by Django 4.0.6 on 2022-08-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_question_points_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='a_number',
            field=models.IntegerField(verbose_name='Answer number'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='This answer is correct'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_number',
            field=models.IntegerField(verbose_name='Question number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('sing', 'Single choice'), ('mult', 'Multiple choice')], max_length=4),
        ),
    ]
