# Generated by Django 4.0.6 on 2022-08-03 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0005_alter_answer_a_number_alter_answer_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taker_name', models.CharField(max_length=250, verbose_name='Taker name')),
                ('quiz_date', models.DateTimeField(auto_now_add=True, verbose_name='Quiz date')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answer')),
                ('q_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question')),
                ('take_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='run.quiztake')),
            ],
        ),
    ]
